<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-21T11:08:19Z" name="Suite1" finished-at="2024-06-21T11:10:09Z" duration-ms="109340">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:tests.TestRunner@a307a8c]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-06-21T11:08:19Z" name="Test" finished-at="2024-06-21T11:10:09Z" duration-ms="109340">
      <class name="tests.TestRunner">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.TestRunner@a307a8c]" started-at="2024-06-21T11:08:18Z" name="setUp" finished-at="2024-06-21T11:08:19Z" duration-ms="1471" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:tests.TestRunner@a307a8c]" started-at="2024-06-21T11:08:19Z" name="setUpClass" finished-at="2024-06-21T11:08:20Z" duration-ms="720" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:tests.TestRunner@a307a8c]" started-at="2024-06-21T11:08:21Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2024-06-21T11:10:09Z" duration-ms="108084" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[FlipKart_HomePage]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: Application is down or username is not displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Application is down or username is not displayed expected [false] but found [true]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: Application is down or username is not displayed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at appmanager.ApplicationManager.initUrlHRM(ApplicationManager.java:219)
at appmanager.HelperBase.checkLogInUserHRM(HelperBase.java:110)
at tests.Hrm.user_launches_the_HRM_application_with(Hrm.java:17)
at âœ½.Given User launches the HRM application with: "prathibhak"(features/Hrm.feature:17)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:tests.TestRunner@a307a8c]" started-at="2024-06-21T11:10:09Z" name="tearDownClass" finished-at="2024-06-21T11:10:09Z" duration-ms="64" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.TestRunner@a307a8c]" started-at="2024-06-21T11:10:09Z" name="tearDown" finished-at="2024-06-21T11:10:09Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite1 -->
</testng-results>
